name: Update Assets

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: 
jobs:
  update-assets:
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repository
      uses: actions/checkout@v3

    - name: Clone chain-registry repository
      run: |
        git clone https://github.com/cosmos/chain-registry.git
        cd chain-registry
        git pull origin master

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10" 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run update script
      run: python scripts/update_assets.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add assets_summary.json
        git commit -m "Update assets_summary.json [skip ci]" || echo "No changes to commit"
        git push
